[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
flux-loom = { path = "flux/crates/loom" } # has updated arrow deps
tempfile = "3.27.0"
redb = "4.1.0"
heed = { version = "0.22.1", default-features = false, features = ["posix-sem"]}
jammdb = "0.11.0"
nut = "0.1.4"

arrow-array = "59.2.0"
arrow-schema = "59.2.0"
arrow-select = "59.2.0"
arrow-cast = "59.2.0"
arrow-csv = "59.2.0"
serde_arrow = { version = "0.14.2", features = ["arrow-59"] }
serde = "1.0.229"

fallible-iterator = "0.3.0"
itertools = "0.15.0"
ouroboros = "0.18.5"


# [[bin]] dependencies
reedline-repl-rs = { version = "1.3.0", features = ["derive"], optional = true }
clap = { version = "4.6.5", features = ["derive", "string"], optional = true }
pulldown-cmark = { version = "0.13.4", optional = true }
comfy-table = { version = "7.2.2", optional = true }
truecalc-workbook = "7"
truecalc-core = "7"

wavefront_obj = "11.0.0"
forsyth = "1.0.1"


[[bin]]
name = "cli"
path = "src/cli/bin.rs"
required-features = ["reedline-repl-rs", "clap", "comfy-table"]
